ERROR discord.app_commands.tree Ignoring exception in command 'test'
Traceback (most recent call last):
  File "/Users/austinares/Desktop/AppleByte/lib/python3.10/site-packages/discord/app_commands/commands.py", line 850, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/Users/austinares/Desktop/AppleByte/src/cogs/general.py", line 14, in online
    await ctx.response.send_message("Online")
  File "/Users/austinares/Desktop/AppleByte/lib/python3.10/site-packages/discord/interactions.py", line 718, in send_message
    await adapter.create_interaction_response(
  File "/Users/austinares/Desktop/AppleByte/lib/python3.10/site-packages/discord/webhook/async_.py", line 219, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/austinares/Desktop/AppleByte/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1240, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/Users/austinares/Desktop/AppleByte/lib/python3.10/site-packages/discord/app_commands/commands.py", line 876, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/Users/austinares/Desktop/AppleByte/lib/python3.10/site-packages/discord/app_commands/commands.py", line 869, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'test' raised an exception: NotFound: 404 Not Found (error code: 10062): Unknown interaction
